src/App.tsx, src/main.tsx, src/style/globalStyles.ts, src/style/theme.ts
close #2 
`style 파일`
- `globalStyles.ts` 설정
- reset.css 와 비슷하게 초기 설정해두었습니다.
- `theme.ts` 설정
- 자주 쓰일 colors, shadows 설정
- theme.ts 에서 사용하시고 싶은게 있다면 위 사진과 같이 사용하면 됩니다~! 
- 보시고 수정할 부분 있으면 코멘트 남겨주세요 😄😄
=> [#2] 초기 글로벌 스타일 설정 

src/App.tsx, src/components/layout/productsList/HotList.tsx, src/components/layout/productsList/HotProduct.tsx, src/components/layout/productsList/NormalCatergory.tsx, src/components/layout/productsList/NormalList.tsx, src/components/layout/productsList/NormalProduct.tsx, src/main.tsx, src/style/globalStyles.ts, src/style/theme.ts
close #3 
- src/components/layout/productsList 폴더에 상품 전체 조회 관련 컴포넌트 파일 생성
- inner의 width가 1280px로 고정이라 px로 작업하였는데 추후에 rem 수정가능
- 별이나 카테고리 이름 옆의 기호 등 아이콘은 추후에 추가예정
=> [#3] 상품 전체 조회 기초 디자인

.eslintrc.json, src/components/common/header/Header.tsx, src/components/layout/Pay/BookingUser.tsx, src/components/layout/Pay/CheckBooking.tsx, src/components/layout/Pay/Payment.tsx
close #32 
- input size up
- 예약자/이용자 유효성 검사 추가
- 체크박스 UI 변경
- 체크하면 예약자 정보 -> 이용자 input
- 전화번호 010-0000-0000 "-" 추가
- 로그인 권장 부분 삭제
- 토글 애니메이션은 실패..(나중에 시간 남으면 재도전)
- 결제 수단 추가 예정
- 커밋하는거 까먹고...있어서 커밋이 별로 없어염...
=> [#32] 결제 페이지 기능 추가 및 보완

.eslintrc.json, src/components/common/header/Header.tsx, src/components/layout/Pay/BookingUser.tsx, src/components/layout/Pay/CheckBooking.tsx, src/components/layout/Pay/OrderedProduct.tsx, src/components/layout/Pay/Payment.tsx, src/pages/OrderedList.tsx
close #35 
결제 완료 화면 UI
구상 완료
- 주문 페이지에 결제 수단, 요청 사항 추가 후 내용 추가 예정
=> [#35] 주문 결과 출력 페이지 UI/구조

src/Router.tsx, src/components/layout/Pay/AllReservation.tsx, src/pages/MyReservation.tsx
close #49 
- 예약 내역 페이지 만들기
-  UI 작업
=> [#49] 예약 내역 페이지 생성

src/components/layout/productsList/CategoryProductsList.tsx, src/components/layout/productsList/ColumnList.tsx, src/components/layout/productsList/MainProductsList.tsx, src/components/layout/productsList/RowProduct.tsx, src/hooks/useProductsData.ts, src/pages/CategoryProducts.tsx, src/pages/Home.tsx
=> Feat: 무한스크롤 observer 추가

src/components/common/header/MenuBtn.tsx, src/components/layout/productsList/CategoryProductsList.tsx, src/components/layout/productsList/ColumnProduct.tsx, src/components/layout/productsList/MainProductsList.tsx, src/hooks/useProductsData.ts, src/types/index.ts
close #53 
- 카테고리 페이지 무한스크롤
- 현재 백엔드 데이터 수량이 너무 적어서 테스팅을 제대로 진행할 수 없음
=> [#53] 카테고리 페이지 무한스크롤

src/components/layout/productsDetail/Calendar.tsx, src/components/layout/productsDetail/PeopleSelector.tsx, src/components/layout/productsDetail/ProductsDetail.tsx
#58 
- 캘린더 컴포넌트 및 인원 체크 컴포넌트 디자인 작업
- 특정 날짜에 reserved=true인 숙소 예약불가 버튼 렌더링
캘린더 부분은 디자인이 안끝나서 더 이쁘게 해볼..게요...
=> [#58] 예약 가능 여부 체크

src/components/layout/productsDetail/Calendar.tsx, src/components/layout/productsDetail/ProductsDetail.tsx, src/types/index.ts
=> [#64] 숙소상세페이지 디자인 작업

package-lock.json, package.json, src/PrivateRoute.tsx, src/api/cart.ts, src/components/common/header/MenuBtn.tsx, src/components/layout/Pay/Payment.tsx, src/components/layout/auth/MyPageForm.tsx, src/components/layout/auth/SigninForm.tsx, src/components/layout/auth/SignupForm.tsx, src/components/layout/cart/CartTotal.tsx, src/hooks/useTokenRefresher.ts
close #72 
alert창 swal로 변경
직접 만든 모달창 변경 원할 시 언제든 말씀 부탁드립니당 !!
=> [#72] 알럿창 swal로 변경

README.md
=> Chore : 리드미 작성(시연영상 제외)

.prettierignore, README.md
=> Chore : 테스트 계정 추가

src/components/layout/productsList/MainProductsList.tsx
=> [#95]카테고리 데이터 순서 변경

src/components/layout/cart/CartItem.tsx, src/components/layout/cart/CartOrder.tsx, src/components/layout/cart/CartTotal.tsx
close #102 
- 장바구니 컴포넌트 분리
- 계산 컴포넌트
- 주문 컴포넌트
- `CartTotal.tsx`에 있던 로직을 계산 & 주문 컴포넌트로 분리하였습니다
- 확인해주시고 코멘트 남겨주세요 ⭐
=> [#102] 장바구니 컴포넌트 분리

src/api/productsList.ts, src/components/common/header/searchBar/SearchBar.tsx, src/components/layout/productsList/CategoryProductsList.tsx, src/components/layout/productsList/ColumnList.tsx, src/components/layout/productsList/MainProductsList.tsx, src/components/layout/productsList/SearchProduct.tsx, src/components/layout/productsList/SearchProductsList.tsx, src/hooks/useObs.ts, src/pages/Home.tsx, src/types/index.ts
close #108
- 카테고리 페이지, 검색 페이지 숙소 디자인 변경
- 검색 버튼 클릭 시 지역선택 초기화
- 무한스크롤 옵저버 범위 증가
변경 전
변경 후
- 페이지 자체 디자인 고민 중
=> [#108] 카테고리 페이지, 검색 페이지 숙소 디자인 변경

src/atoms/cartAtom.ts, src/components/common/AuthHeader.tsx, src/components/layout/Pay/BookingInfo.tsx, src/components/layout/Pay/OrderedProduct.tsx, src/components/layout/Pay/Payment.tsx, src/components/layout/cart/CartItem.tsx, src/components/layout/cart/CartOrder.tsx, src/components/layout/productsDetail/ProductsDetail.tsx, src/pages/OrderedList.tsx, src/types/index.ts
close #114 
- 장바구니 및 예약하기 Api 변경에 따라 코드 수정 및 type 변경
- 숙소 추가 정보 진행중
@seacrab808  예약 Api 쪽 원래는 부족한 정보 프론트에서 리코일로 전부 담아서 줬는데 이제는 roomCode, startDate, endDate 밖에 안넘겨줘서, bookingInfo return 부분에서 오류가 나서 오류 부분 주석처리 해놓은 상태입니다. 확인해보시고 말씀해주세요!
=> [#114] 숙소상세페이지 추가작업

src/components/common/AuthHeader.tsx, src/components/layout/productsDetail/ProductsDetail.tsx
=> Fix: 로그인 여부에 따라 숙소상세정보 차이 있게 제공

src/components/layout/cart/CartItem.tsx, src/components/layout/cart/CartOrder.tsx, src/types/index.ts
close #115 
- 백엔드 API 수정으로 장바구니 API 수정하였습니다
- 프리뷰로 에러나는지 확인해주시고 코멘트 달아주세욥!
=> [#115] 장바구니 API 수정

src/components/layout/productsDetail/ProductAmenities.tsx, src/components/layout/productsDetail/ProductsDetail.tsx, src/types/index.ts
#122 
추가정보 디자인 작업중
예약하기 api 변경에 따른 타입 추가(cartId = -1)
=> [#122] 숙소상세페이지 추가작업

src/components/layout/productsDetail/ProductAmenities.tsx, src/components/layout/productsDetail/RoomOptionModal.tsx
#122 
- Amenity 정보 아이콘 적용 및 값 false시 취소선 적용
- Option 정보 아이콘 적용 및 값 false시 취소선 적용
- Option 정보 중 foodPlace(음식점) string값이 '없음'일 경우 취소선 적용
- Option 정보 레이아웃 수정
=> [#122] 숙소상세페이지 수정

.eslintrc.json, src/components/layout/Pay/AllReservation.tsx, src/components/layout/Pay/BookingInfo.tsx, src/components/layout/Pay/OrderedProduct.tsx, src/components/layout/Pay/Payment.tsx
=> [#140] 결제 페이지 유효성 수정

src/api/cart.ts, src/atoms/cartAtom.ts, src/components/layout/cart/CartItem.tsx, src/components/layout/cart/CartNoItem.tsx, src/components/layout/cart/CartOrder.tsx, src/types/index.ts
=> [#131] 장바구니 API 변경으로 인한 로직 수정

src/components/layout/Pay/BookingInfo.tsx, src/components/layout/Pay/OrderedProduct.tsx, src/components/layout/Pay/Payment.tsx
close #143
이중 map때문에 제곱으로 출력된거 수정함
=> [#143] 이중 map 제거

README.md, src/components/layout/cart/CartItem.tsx
=> [#146] 장수빈 README 작성

src/components/layout/Pay/AllReservation.tsx
=> [#148] key값 에러 해결
